#docker compose -f "docker-compose.yml" up -d --build 

services:
  data:
    image: mongo:8.0.3-noble
    ports:
      - 27017:27017
    networks:
      - grafiles
    container_name: grafiles-data
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
  back:
    build: 
      context: .
    ports:
      - 3000:3000
    networks:
      - grafiles
    container_name: grafiles-backend
    depends_on:
      - data

networks:
  grafiles:
